spring.application.name=desafio-pleno
## Banco
spring.datasource.url=jdbc:postgresql://localhost:5432/desafio
spring.datasource.username=prodabel
spring.datasource.password=prodabel123
spring.jpa.hibernate.ddl-auto=update
## Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
